//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SK_Lightworks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SK_Lightworks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap LED_BlueOff1 {
            get {
                object obj = ResourceManager.GetObject("LED_BlueOff1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_BlueOff2 {
            get {
                object obj = ResourceManager.GetObject("LED_BlueOff2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_BlueOff3 {
            get {
                object obj = ResourceManager.GetObject("LED_BlueOff3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_BlueOff4 {
            get {
                object obj = ResourceManager.GetObject("LED_BlueOff4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_BlueOff5 {
            get {
                object obj = ResourceManager.GetObject("LED_BlueOff5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_BlueOff6 {
            get {
                object obj = ResourceManager.GetObject("LED_BlueOff6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_BlueOff7 {
            get {
                object obj = ResourceManager.GetObject("LED_BlueOff7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_BlueOff8 {
            get {
                object obj = ResourceManager.GetObject("LED_BlueOff8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_BlueOn1 {
            get {
                object obj = ResourceManager.GetObject("LED_BlueOn1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_BlueOn2 {
            get {
                object obj = ResourceManager.GetObject("LED_BlueOn2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_BlueOn3 {
            get {
                object obj = ResourceManager.GetObject("LED_BlueOn3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_BlueOn4 {
            get {
                object obj = ResourceManager.GetObject("LED_BlueOn4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_BlueOn5 {
            get {
                object obj = ResourceManager.GetObject("LED_BlueOn5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_BlueOn6 {
            get {
                object obj = ResourceManager.GetObject("LED_BlueOn6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_BlueOn7 {
            get {
                object obj = ResourceManager.GetObject("LED_BlueOn7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_BlueOn8 {
            get {
                object obj = ResourceManager.GetObject("LED_BlueOn8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_GreenOff1 {
            get {
                object obj = ResourceManager.GetObject("LED_GreenOff1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_GreenOff2 {
            get {
                object obj = ResourceManager.GetObject("LED_GreenOff2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_GreenOff3 {
            get {
                object obj = ResourceManager.GetObject("LED_GreenOff3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_GreenOff4 {
            get {
                object obj = ResourceManager.GetObject("LED_GreenOff4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_GreenOff5 {
            get {
                object obj = ResourceManager.GetObject("LED_GreenOff5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_GreenOff6 {
            get {
                object obj = ResourceManager.GetObject("LED_GreenOff6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_GreenOff7 {
            get {
                object obj = ResourceManager.GetObject("LED_GreenOff7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_GreenOff8 {
            get {
                object obj = ResourceManager.GetObject("LED_GreenOff8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_GreenOn1 {
            get {
                object obj = ResourceManager.GetObject("LED_GreenOn1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_GreenOn2 {
            get {
                object obj = ResourceManager.GetObject("LED_GreenOn2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_GreenOn3 {
            get {
                object obj = ResourceManager.GetObject("LED_GreenOn3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_GreenOn4 {
            get {
                object obj = ResourceManager.GetObject("LED_GreenOn4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_GreenOn5 {
            get {
                object obj = ResourceManager.GetObject("LED_GreenOn5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_GreenOn6 {
            get {
                object obj = ResourceManager.GetObject("LED_GreenOn6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_GreenOn7 {
            get {
                object obj = ResourceManager.GetObject("LED_GreenOn7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_GreenOn8 {
            get {
                object obj = ResourceManager.GetObject("LED_GreenOn8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_RedOff1 {
            get {
                object obj = ResourceManager.GetObject("LED_RedOff1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_RedOff2 {
            get {
                object obj = ResourceManager.GetObject("LED_RedOff2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_RedOff3 {
            get {
                object obj = ResourceManager.GetObject("LED_RedOff3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_RedOff4 {
            get {
                object obj = ResourceManager.GetObject("LED_RedOff4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_RedOff5 {
            get {
                object obj = ResourceManager.GetObject("LED_RedOff5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_RedOff6 {
            get {
                object obj = ResourceManager.GetObject("LED_RedOff6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_RedOff7 {
            get {
                object obj = ResourceManager.GetObject("LED_RedOff7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_RedOff8 {
            get {
                object obj = ResourceManager.GetObject("LED_RedOff8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_RedOn1 {
            get {
                object obj = ResourceManager.GetObject("LED_RedOn1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_RedOn2 {
            get {
                object obj = ResourceManager.GetObject("LED_RedOn2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_RedOn3 {
            get {
                object obj = ResourceManager.GetObject("LED_RedOn3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_RedOn4 {
            get {
                object obj = ResourceManager.GetObject("LED_RedOn4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_RedOn5 {
            get {
                object obj = ResourceManager.GetObject("LED_RedOn5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_RedOn6 {
            get {
                object obj = ResourceManager.GetObject("LED_RedOn6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_RedOn7 {
            get {
                object obj = ResourceManager.GetObject("LED_RedOn7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_RedOn8 {
            get {
                object obj = ResourceManager.GetObject("LED_RedOn8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_YellowOff1 {
            get {
                object obj = ResourceManager.GetObject("LED_YellowOff1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_YellowOff2 {
            get {
                object obj = ResourceManager.GetObject("LED_YellowOff2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_YellowOff3 {
            get {
                object obj = ResourceManager.GetObject("LED_YellowOff3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_YellowOff4 {
            get {
                object obj = ResourceManager.GetObject("LED_YellowOff4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_YellowOff5 {
            get {
                object obj = ResourceManager.GetObject("LED_YellowOff5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_YellowOff6 {
            get {
                object obj = ResourceManager.GetObject("LED_YellowOff6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_YellowOff7 {
            get {
                object obj = ResourceManager.GetObject("LED_YellowOff7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_YellowOff8 {
            get {
                object obj = ResourceManager.GetObject("LED_YellowOff8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_YellowOn1 {
            get {
                object obj = ResourceManager.GetObject("LED_YellowOn1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_YellowOn2 {
            get {
                object obj = ResourceManager.GetObject("LED_YellowOn2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_YellowOn3 {
            get {
                object obj = ResourceManager.GetObject("LED_YellowOn3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_YellowOn4 {
            get {
                object obj = ResourceManager.GetObject("LED_YellowOn4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_YellowOn5 {
            get {
                object obj = ResourceManager.GetObject("LED_YellowOn5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_YellowOn6 {
            get {
                object obj = ResourceManager.GetObject("LED_YellowOn6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_YellowOn7 {
            get {
                object obj = ResourceManager.GetObject("LED_YellowOn7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LED_YellowOn8 {
            get {
                object obj = ResourceManager.GetObject("LED_YellowOn8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
